FROM ubuntu

# File Author / Maintainer
MAINTAINER srinath_reddy

# Update the repository sources list
RUN apt-get update

# Install and run apache
RUN apt-get install -y apache2 && apt-get clean

EXPOSE 80
CMD apachectl -D FOREGROUND
